### ISSUE TITLE
i get that error , how to fix it ?

### ISSUE THREAD

**Issue by axroromonov44** [Dynamsoft/capture-vision-flutter-samples#8]
The 'com.dynamsoft/barcode_result_observer' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

**Comment by Dynamsoft-Henry** [comment]
Hi @axroromonov 

We fixed this issue in the v1.2.3 branch but it is still not released. For some reason, we can't confirm the release date of the 1.2.3 version currently. I think the change logs of v1.2.3 branch might help you debug this issue.

**Comment by axroromonov44** [comment]
and I have a question in terms of performance , the device gets very hot when the camera is opened on iOS , how to normal it ?

**Comment by Dynamsoft-Henry** [comment]
Hi @axroromonov. That's because of the high occupancy of the CPU. The library will continuously process the video frames after you `startScanning`. If you don't `stopScanning`, the device does get hot.

We have an API to control the barcode decoding interval, which might work for you. The API is currently not added to the Flutter platform. Please let me know if you want to try the API. We can add it.

However, I think the best solution is to `stopScanning` when you don't want to process the video frames.

**Comment by axroromonov44** [comment]
thank you for response  , I will read the data-matrix through your packages, it may take a long time, for example, I may have to read 100-200 matrices at the same time, at this time my phone will be as hot as the sun, I like this package but it is a bit difficult in terms of performance

**Comment by axroromonov44** [comment]
Error (Xcode): Building for 'iOS-simulator', but linking in dylib (/Users/it-admin/Documents/git_lab/agrokomak_mobile/ios/Pods/DynamsoftBarcodeReader/DynamsoftBarcodeReader.framework/DynamsoftBarcodeReader) built for 'iOS'

Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)

Could not build the application for the simulator.
Error launching application on iPad Pro (11-inch) (4th generation). 


When I try to run it on iPad, I have such a problem, how can I fix it?

**Comment by Dynamsoft-Henry** [comment]
Hi @axroromonov 

We updated the 1.2.3 branch to support the simulator.

For the iPad issue, we might need some more time.

**Comment by axroromonov44** [comment]
this is the same problem in the simulator as well as in the real iPad

**Comment by Dynamsoft-Henry** [comment]
Hi @axroromonov 
We tested our changes on the iPad and it is working fine now. We uploaded the changes in the 1.2.3 branch, would you like to have a look at it?

**Comment by axroromonov44** [comment]
Yes, I'm a little confused, it worked, but it doesn't work in the simulator

**Comment by axroromonov44** [comment]
What are the changes in this version? in 1.2.3

**Comment by axroromonov44** [comment]
I still see version 1.2.2

**Comment by Dynamsoft-Henry** [comment]
If you are still in 1.2.2, please remove your workspace, pods folder and pod lock file (all the files created by pod install).

Run the `pod update`, and then run `pod install`.

We added the support of the architectures that are required by simulators.

**Comment by axroromonov44** [comment]
pub.dev still has 1.2.2, you can check it

**Comment by axroromonov44** [comment]
<img width="1092" alt="Screenshot 2023-11-27 at 12 36 39" src="https://github.com/Dynamsoft/capture-vision-flutter/assets/76530966/e10c9736-e4da-46ec-b955-2de7fedcda97">

**Comment by Dynamsoft-Henry** [comment]
![image](https://github.com/Dynamsoft/capture-vision-flutter/assets/78675724/bf81b98f-3c40-4fed-a033-55a5a2f378cc)

We didn't talk about the pub.dev. We updated the changes on GitHub 1.2.3 branch. Currently, the formal release of the 1.2.3 version is still not arranged.

**Comment by axroromonov44** [comment]
sorry ,I thought it was on pub.dev . Cool , I will try it . Do you have any communities ?

**Comment by Dynamsoft-Henry** [comment]
Do you mean a community edition? Sorry, we don't.

**Comment by axroromonov44** [comment]
ok got it , good luck !
